// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1MZAH7-gIflm2haW77hJ_A_B-GgZhluw',
    appId: '1:751214631491:web:9e4a5a451d1a8351a452f6',
    messagingSenderId: '751214631491',
    projectId: 'pulsefit-8b6cb',
    authDomain: 'pulsefit-8b6cb.firebaseapp.com',
    storageBucket: 'pulsefit-8b6cb.firebasestorage.app',
    measurementId: 'G-PHFCEDKN3Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCu3O--bVpcX-vEK00Cbqc73D8mevVtrJU',
    appId: '1:751214631491:android:9b82b2d08df206d8a452f6',
    messagingSenderId: '751214631491',
    projectId: 'pulsefit-8b6cb',
    storageBucket: 'pulsefit-8b6cb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6rGIjH39x-l5G5lBucuJVs8zBVfmoXhc',
    appId: '1:751214631491:ios:ae979041bc4ae70aa452f6',
    messagingSenderId: '751214631491',
    projectId: 'pulsefit-8b6cb',
    storageBucket: 'pulsefit-8b6cb.firebasestorage.app',
    iosBundleId: 'com.example.fitZone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6rGIjH39x-l5G5lBucuJVs8zBVfmoXhc',
    appId: '1:751214631491:ios:ae979041bc4ae70aa452f6',
    messagingSenderId: '751214631491',
    projectId: 'pulsefit-8b6cb',
    storageBucket: 'pulsefit-8b6cb.firebasestorage.app',
    iosBundleId: 'com.example.fitZone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1MZAH7-gIflm2haW77hJ_A_B-GgZhluw',
    appId: '1:751214631491:web:ce26b633dd2d3341a452f6',
    messagingSenderId: '751214631491',
    projectId: 'pulsefit-8b6cb',
    authDomain: 'pulsefit-8b6cb.firebaseapp.com',
    storageBucket: 'pulsefit-8b6cb.firebasestorage.app',
    measurementId: 'G-4JHSNNLEEM',
  );
}
