// Mocks generated by Mockito 5.4.5 from annotations
// in fit_zone/test/ui/food/view_model/categories_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:fit_zone/core/api/api_result.dart' as _i5;
import 'package:fit_zone/data/model/food/category.dart' as _i6;
import 'package:fit_zone/domain/repo_contract/food_repo/get_categories_of_meals_repo.dart'
    as _i2;
import 'package:fit_zone/domain/use_cases/food_usecase/get_categories_of_meals_usecase.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeGetCategoriesOfMealsRepo_0 extends _i1.SmartFake
    implements _i2.GetCategoriesOfMealsRepo {
  _FakeGetCategoriesOfMealsRepo_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetCategoriesOfMealsUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetCategoriesOfMealsUsecase extends _i1.Mock
    implements _i3.GetCategoriesOfMealsUsecase {
  MockGetCategoriesOfMealsUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.GetCategoriesOfMealsRepo get getCategoriesOfMealsRepo =>
      (super.noSuchMethod(
            Invocation.getter(#getCategoriesOfMealsRepo),
            returnValue: _FakeGetCategoriesOfMealsRepo_0(
              this,
              Invocation.getter(#getCategoriesOfMealsRepo),
            ),
          )
          as _i2.GetCategoriesOfMealsRepo);

  @override
  _i4.Future<_i5.ApiResult<List<_i6.Category>>> execute() =>
      (super.noSuchMethod(
            Invocation.method(#execute, []),
            returnValue: _i4.Future<_i5.ApiResult<List<_i6.Category>>>.value(
              _i7.dummyValue<_i5.ApiResult<List<_i6.Category>>>(
                this,
                Invocation.method(#execute, []),
              ),
            ),
          )
          as _i4.Future<_i5.ApiResult<List<_i6.Category>>>);
}
